=== namm-standards/namm-json/schema/item.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://standards.namm.org/schema/2020.1/item.json",
    "type": "object",
    "title": "Item",
    "description": "Item v2020.1",
    "additionalProperties": false,
    "properties": {
        "Version": {
            "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Version"
        },
        "Timestamp": {
            "type": "string"
        },
        "Id": {
            "type": "string"
        },
        "SupplierId": {
            "type": "string"
        },
        "Items": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/Item"
            }
        }
    },
    "required": [],
    "definitions": {
        "Item": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "SupplierItemId": {
                    "type": "string"
                },
                "SupplierModel": {
                    "type": "string"
                },
                "SupplierItemDesc": {
                    "type": "string"
                },
                "Kit": {
                    "type": "string",
                    "enum": [
                        "Y",
                        "N"
                    ]
                },
                "KitComponentOnly": {
                    "type": "string",
                    "enum": [
                        "Y",
                        "N"
                    ]
                },
                "Serialized": {
                    "type": "string",
                    "enum": [
                        "Y",
                        "N"
                    ]
                },
                "BrandName": {
                    "type": "string"
                },
                "CountryOrigin": {
                    "type": "string",
                    "maxLength": 2,
                    "minLength": 2
                },
                "Length": {
                    "type": "number"
                },
                "Width": {
                    "type": "number"
                },
                "Height": {
                    "type": "number"
                },
                "DimUOM": {
                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/DimUOM"
                },
                "Weight": {
                    "type": "number"
                },
                "WeightUOM": {
                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/WeightUOM"
                },
                "AnnounceDate": {
                    "type": "string",
                    "format": "date"
                },
                "AvailableDate": {
                    "type": "string",
                    "format": "date"
                },
                "UnavailableDate": {
                    "type": "string",
                    "format": "date"
                },
                "EndOfProductionDate": {
                    "type": "string",
                    "format": "date"
                },
                "ReplacementID": {
                    "type": "string"
                },
                "WarrantyPartTerm": {
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 0
                },
                "WarrantyPartUOM": {
                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/TermUOM"
                },
                "WarrantyLabTerm": {
                    "type": "integer",
                    "maximum": 255,
                    "minimum": 0
                },
                "WarrantyLabUOM": {
                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/TermUOM"
                },
                "Condition": {
                    "type": "string"
                },
                "Barcodes": {
                    "type": "array",
                    "items": {
                        "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Barcode"
                    }
                },
                "Pricing": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "type": {
                                "type": "string",
                                "enum": [
                                    "MSRP",
                                    "MAP",
                                    "Cost"
                                ]
                            },
                            "Currency": {
                                "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/CurrencyCode"
                            },
                            "Qty": {
                                "type": "integer",
                                "maximum": 255,
                                "minimum": 0
                            }
                        },
                        "required": [
                            "type",
                            "Currency"
                        ]
                    }
                },
                "Containers": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "Type": {
                                "type": "string"
                            },
                            "Length": {
                                "type": "number"
                            },
                            "Width": {
                                "type": "number"
                            },
                            "Height": {
                                "type": "number"
                            },
                            "DimUOM": {
                                "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/DimUOM"
                            },
                            "Weight": {
                                "type": "number"
                            },
                            "WeightUOM": {
                                "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/WeightUOM"
                            },
                            "UOM": {
                                "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/QtyUOM"
                            },
                            "QtyPerUOM": {
                                "type": "integer",
                                "maximum": 65535,
                                "minimum": 0
                            },
                            "Barcodes": {
                                "type": "array",
                                "items": {
                                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Barcode"
                                }
                            }
                        },
                        "required": [
                            "Type",
                            "Length",
                            "Width",
                            "Height",
                            "DimUOM",
                            "Weight",
                            "WeightUOM",
                            "UOM",
                            "QtyPerUOM"
                        ]
                    }
                },
                "KitItems": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "SupplierItemId": {
                                "type": "string"
                            },
                            "Qty": {
                                "type": "number"
                            },
                            "UOM": {
                                "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/QtyUOM"
                            },
                            "Barcodes": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Barcode"
                                }
                            }
                        },
                        "required": [
                            "SupplierItemId",
                            "Qty",
                            "UOM"
                        ]
                    }
                },
                "MarketingInfo": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "PrimaryCategory": {
                            "type": "string"
                        },
                        "ProductURL": {
                            "type": "string",
                            "format": "uri"
                        },
                        "ItemDescLong": {
                            "type": "string"
                        },
                        "SecondaryCategories": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "Bullets": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "Media": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                                "Images": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Image"
                                    }
                                },
                                "Videos": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Video"
                                    }
                                },
                                "Documents": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Document"
                                    }
                                },
                                "Audios": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Audio"
                                    }
                                }
                            }
                        },
                        "Keywords": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "required": [
                        "PrimaryCategory"
                    ]
                },
                "ExtendedAttributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExtendedAttribute"
                    }
                },
                "RelatedItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/RelatedItem"
                    }
                },
                "ItemFamily": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "property": {
                            "type": "string"
                        },
                        "code": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "property",
                        "code"
                    ]
                },
                "Availability": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "QtyOnHand": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "Available": {
                            "type": "string",
                            "enum": [
                                "YES",
                                "NO",
                                "LOW",
                                "MEDIUM",
                                "HIGH"
                            ]
                        },
                        "QueryURL": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": [
                        "Available"
                    ]
                },
                "Prop65Message": {
                    "type": "string"
                },
                "Prop65Chemical": {
                    "type": "string"
                }
            },
            "required": []
        },
        "RelatedItem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "similar",
                        "accessory",
                        "ThirdParty"
                    ]
                },
                "included": {
                    "type": "string",
                    "enum": [
                        "Y",
                        "N"
                    ]
                },
                "SupplierItemId": {
                    "type": "string"
                },
                "Barcode": {
                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Barcode"
                }
            }
        },
        "Image": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "URL": {
                    "type": "string",
                    "format": "uri"
                },
                "Audience": {
                    "type": "string",
                    "enum": [
                        "Consumer",
                        "Dealer"
                    ]
                },
                "View": {
                    "type": "string",
                    "enum": [
                        "Front cover",
                        "Preface",
                        "Back cover",
                        "Contents",
                        "Primary"
                    ]
                },
                "Caption": {
                    "type": "string"
                },
                "CarouselSequence": {
                    "type": "integer"
                }
            }
        },
        "Video": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "URL": {
                    "type": "string",
                    "format": "uri"
                },
                "Audience": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "flv",
                        "mp4",
                        "mov",
                        "avi"
                    ]
                },
                "Caption": {
                    "type": "string"
                }
            }
        },
        "Document": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "URL": {
                    "type": "string",
                    "format": "uri"
                },
                "Audience": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "pdf",
                        "doc",
                        "docx",
                        "txt"
                    ]
                },
                "Caption": {
                    "type": "string"
                }
            }
        },
        "Audio": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "URL": {
                    "type": "string",
                    "format": "uri"
                },
                "Audience": {
                    "type": "string",
                    "enum": [
                        "Consumer"
                    ]
                },
                "type": {
                    "type": "string"
                },
                "Caption": {
                    "type": "string"
                }
            }
        },
        "ExtendedAttribute": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Value": {
                    "additionalProperties": false,
                    "anyOf": [
                        {
                            "$ref": "#/definitions/Contributor"
                        },
                        {
                            "type": "string",
                            "title": "Extended Attribute Name",
                            "description": "This might have enums?"
                        },
                        {
                            "type": "number"
                        }
                    ]
                }
            }
        },
        "Contributor": {
            "type": "object",
            "properties": {
                "Primary": {
                    "type": "boolean"
                },
                "Contribution": {
                    "type": "string",
                    "enum": [
                        "Author",
                        "Artist",
                        "Composer",
                        "Arranger"
                    ]
                },
                "ContributorName": {
                    "type": "string"
                },
                "ContributorNameReversed": {
                    "type": "string"
                }
            }
        }
    }
}

=== namm-standards/namm-json/examples/item_example.json
{
    "Version" :2020.1,
    "Timestamp": "2020-01-04T15:52:29.073",
    "Id": "03C8CA92-6413-4B7E-B5B1-F6903AD8327A",
    "SupplierId": "0670716000009",
    "Items": [
        {
            "SupplierItemId": "SP170WH",
            "SupplierModel": "SP170WH",
            "SupplierItemDesc": "Piano, pure and simple",
            "Kit": "N",
            "Serialized": "Y",
            "BrandName": "KORG",
            "CountryOrigin": "CN",
            "Length": 0.0000,
            "Width": 0.0000,
            "Height": 0.0000,
            "DimUOM": "Inches",
            "Weight": 0,
            "WeightUOM": "Pounds",
            "AnnounceDate": "2009-12-15",
            "AvailableDate": "2009-12-15",
            "UnavailableDate": "2011-05-23",
            "WarrantyPartTerm": 365,
            "WarrantyPartUOM": "Days",
            "WarrantyLabTerm": 0,
            "WarrantyLabUOM": "Days",
            "Barcodes": [
                {
                    "ID": "4959112073463",
                    "Type": "GTIN-13"
                }
            ],
            "Pricing": [
                {
                    "type": "MSRP",
                    "Currency": "USD",
                    "Value": 600.00
                },
                {
                    "type": "MAP",
                    "Currency": "USD",
                    "Value": 500.00
                },
                {
                    "type": "Cost",
                    "Currency": "USD",
                    "Qty": 1,
                    "Value": 250.00
                }
            ],
            "Containers": [
                {
                    "Type": "Each",
                    "Length": 57.2500,
                    "Width": 17.2500,
                    "Height": 8.2500,
                    "DimUOM": "Inches",
                    "Weight": 33.7500,
                    "WeightUOM": "Pounds",
                    "UOM": "Each",
                    "QtyPerUOM": 1,
                    "Barcodes": [
                        {
                            "ID": "4959112073463",
                            "Type": "GTIN-13"
                        }
                    ]
                }
            ],
            "MarketingInfo": {
            "PrimaryCategory": "4018162506",
            "ProductURL": "https://www.korg.com/sp170",
            "ItemDescLong": "Offering an affordable, portable and rewarding piano solution, the streamlined SP-170 features an authentic piano feel and 10 captivating sounds - including two superb grands - to satisfy the student, novice, or seasoned player. The clean, fresh design omits the traditional control panel, emphasizing instead the comfortable keyboard and satisfying sound.",
            "Bullets":  [
                "Korg's 88-key Natural Weighted Hammer Action (NH) keyboard offers a true piano touch",
                "10 Sounds: Piano x 2; E. Piano x 2; Harpsichord; Clavi; Vibraphone; Pipe Organ; Jazz Organ; Strings",
                "Reverb + Chorus effects; Transpose; Pitch Control; MIDI functions (MIDI Out); Damper pedal included",
                "Built-in sound system: 9 Watt stereo amplifier, 2 full-range speakers; 2 line/headphone outputs",
                "Elegant white finish; optional matching wooden stand (SPST-1W-WH) available"
              ],
            "Media": {
                "Images": [
                   {
                        "Audience": "Consumer",
                        "View": "Primary",
                        "URL": "http://dealers.korgusa.com/images/product/SP170WH.png"
                    }
                ]
            }
            
          },
          "RelatedItems" : [
              {
                "included": "Y",
                "type": "accessory",
                "SupplierItemId": "405016000",
                "Barcode": {
                  "ID": "4959112073463",
                  "Type": "GTIN-13"
                }
              },
              {
                "included": "Y",
                "type": "accessory",
                "SupplierItemId": "500600006510",
                "Barcode": {
                  "ID": "4959112073463",
                  "Type": "GTIN-13"
                }
              },
              {
                "included": "N",
                "type": "accessory",
                "SupplierItemId": "510C9018",
                "Barcode": {
                  "ID": "4959112073463",
                  "Type": "GTIN-13"
                }
              }
          ],
          "Availability": {
            "Available": "YES"
          }
        },

        {
          "SupplierItemId": "SPST1WWH",
          "SupplierModel": "SPST1WWH",
          "SupplierItemDesc": "White stand for SP170WH",
          "Kit": "N",
          "KitComponentOnly": "Y",
          "Serialized": "N",
          "BrandName": "KORG",
          "CountryOrigin": "CN",
          "Length": 0.0000,
          "Width": 0.0000,
          "Height": 0.0000,
          "DimUOM": "Inches",
          "Weight": 0,
          "WeightUOM": "Pounds",
          "AnnounceDate": "2009-12-15",
          "AvailableDate": "2009-12-15",
          "WarrantyPartTerm": 365,
          "WarrantyPartUOM": "Days",
          "WarrantyLabTerm": 0,
          "WarrantyLabUOM": "Days",
            "Barcodes": [
                {
                    "ID": "4959112073487",
                    "Type": "GTIN-13"
                }
            ],
            "Pricing": [
              {
                "type": "MSRP",
                "Currency": "USD",
                "Value": 125.00
            },
              {
                "type": "MAP",
                "Currency": "USD",
                "Value": 62.00
            },
              {
                "type": "Cost",
                "Currency": "USD",
                "Qty": 1,
                "Value": 31.00
            }
            ],
            "Containers": [
                {
                    "Type": "Each",
                    "Length": 57.2500,
                    "Width": 17.6250,
                    "Height": 4.0200,
                    "DimUOM": "Inches",
                    "Weight": 24.7000,
                    "WeightUOM": "Pounds",
                    "UOM": "Each",
                    "QtyPerUOM": 1,
                    "Barcodes": [
                        {
                            "ID": "4959112073487",
                            "Type": "GTIN-13"
                        }
                    ]
                }
            ],
            "MarketingInfo": {
            "PrimaryCategory": "1018176583",
            "Bullets": [],
            "Media": {
                "Images": [
                    {
                        "Audience": "Consumer",
                        "View": "Primary",
                        "URL": "http://dealers.korgusa.com/images/product/SPST1WWH.png"
                    }
                ]
            }
          },
          "Availability": {
            "Available": "YES"
          }
        },
        {
          "SupplierItemId": "SP170WHK",
          "SupplierModel": "SP170WHK",
          "SupplierItemDesc": "White stand and SP170WH Bundle",
          "Kit": "Y",
          "Serialized": "N",
          "BrandName": "KORG",
          "CountryOrigin": "CN",
          "AnnounceDate": "2009-12-15",
          "AvailableDate": "2009-12-15",
          "WarrantyPartTerm": 365,
          "WarrantyPartUOM": "Days",
          "WarrantyLabTerm": 0,
          "WarrantyLabUOM": "Days",
            "Barcodes": [
                {
                    "ID": "4959112073490",
                    "Type": "GTIN-13"
                }
            ],
            "Pricing": [
            
              {
                "type": "MSRP",
                "Currency": "USD",
                "Value": 725.00
              },
              {
                "type": "MAP",
                "Currency": "USD",
                "Value": 525.00
              },
              {
                "type": "Cost",
                "Currency": "USD",
                "Qty": 1,
                "Value": 270.00
              }
          ],
            
          "KitItems" :  [            
              {
                "SupplierItemId": "SP170WH",
                "Qty": 1,
                "UOM": "Each",
                "Barcodes": [
                    {
                        "ID": "4959112073463",
                        "Type": "GTIN-13"
                    }
                ]
              },
            {
                "SupplierItemId": "SPST1WWH",
                "Qty": 1,
                "UOM": "Each",
                    "Barcodes": [
                        {
                            "ID": "4959112073487",
                            "Type": "GTIN-13"
                        }
                    ]
                }
            ],
          
          "MarketingInfo": {
            "PrimaryCategory": "4018162506",
            "ProductURL": "https://www.korg.com/sp170",
            "ItemDescLong": "Offering an affordable, portable and rewarding piano solution, the streamlined SP-170 features an authentic piano feel and 10 captivating sounds - including two superb grands - to satisfy the student, novice, or seasoned player. The clean, fresh design omits the traditional control panel, emphasizing instead the comfortable keyboard and satisfying sound.",
            "Bullets":  [
                "Korg's 88-key Natural Weighted Hammer Action (NH) keyboard offers a true piano touch",
                "10 Sounds: Piano x 2; E. Piano x 2; Harpsichord; Clavi; Vibraphone; Pipe Organ; Jazz Organ; Strings",
                "Reverb + Chorus effects; Transpose; Pitch Control; MIDI functions (MIDI Out); Damper pedal included",
                "Built-in sound system: 9 Watt stereo amplifier, 2 full-range speakers; 2 line/headphone outputs",
                "Elegant white finish; optional matching wooden stand (SPST-1W-WH) available"
              ],
