=== namm-standards/namm-json/schema/po_status_request.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://standards.namm.org/schema/2020.1/po_status_request.json",
    "type": "object",
    "title": "NAMM_POStatusRequest",
    "additionalProperties": false,
    "properties": {
        "Version": {
            "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Version"
        },
        "Id": {
            "type": "string",
            "description": "Document ID"
        },
        "Timestamp": {
            "type": "string",
            "description": "Document Time stamp",
            "format": "date-time"
        },
        "Supplier": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "PartyId": {
                    "type": "string"
                },
                "PartyIdType": {
                    "type": "string",
                    "enum": [
                        "GLN",
                        "NAMM"
                    ]
                }
            },
            "required": [
                "PartyId"
            ]
        },
        "SoldTo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "PartyId": {
                    "type": "string"
                },
                "PartyIdType": {
                    "type": "string",
                    "enum": [
                        "GLN",
                        "NAMM"
                    ]
                }
            },
            "required": [
                "PartyId"
            ]
        },
        "BuyerOrderIds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": []
}

=== namm-standards/namm-json/examples/po_status_request_example.json
{
  "Version": 2020.1,
    "Id": "b8917d4c-22e5-4045-8b3c-39ce6e82234a",
    "Timestamp": "2020-01-02T10:34:02-0500",
    "Supplier": {
        "PartyId": "0670716000009",
        "PartyIdType": "GLN"
    },
  "SoldTo": {
    "PartyId": "NAMM*000010298975",
    "PartyIdType" : "NAMM"
  },
  "BuyerOrderIds": [
    "65642X"
    ]
}
