=== namm-standards/namm-json/schema/po_status.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://standards.namm.org/schema/2020.1/po_status.json",
    "type": "object",
    "title": "NAMM_PO_Status",
    "additionalProperties": false,
    "properties": {
        "Version": {
            "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Version"
        },
        "Id": {
            "type": "string",
            "description": "Document ID",
            "maxLength": 50
        },
        "Timestamp": {
            "type": "string",
            "format": "date-time"
        },
        "POStatusRequestId": {
            "type": "string",
            "description": "PO ID of status request",
            "maxLength": 50
        },
        "BuyerOrderId": {
            "type": "string",
            "description": "Buyer order ID",
            "maxLength": 25
        },
        "DateOrdered": {
            "type": "string",
            "description": "Order Date",
            "format": "date"
        },
        "BuyerName": {
            "type": "string",
            "description": "Buyer Name"
        },
        "Supplier": {
            "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Party"
        },
        "SoldTo": {
            "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Party"
        },
        "StatusCode": {
            "$ref": "#/definitions/StatusCode"
        },
        "PaymentTerms": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "StatusCode": {
                    "type": "string",
                    "description": "Payment status code"
                },
                "StatusMessage": {
                    "type": "string"
                },
                "TermsCode": {
                    "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/TermsCode"
                }
            },
            "required": [
                "StatusCode",
                "StatusMessage",
                "TermsCode"
            ]
        },
        "ShipmentTerms": {
            "type": "object",
            "additionalProperties": {
                "not": {}
            },
            "properties": {
                "StatusCode": {
                    "type": "string",
                    "description": "Shipment status code"
                }
            }
        },
        "ShipTo": {
            "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Party"
        },
        "Items": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "POLineNbr": {
                        "type": "integer",
                        "description": "Item line number"
                    },
                    "SequenceNbr": {
                        "type": "integer",
                        "description": "Item sequence number"
                    },
                    "StatusCode": {
                        "$ref": "#/definitions/StatusCode"
                    },
                    "StatusMessage": {
                        "type": "string",
                        "description": "Item Status Message"
                    },
                    "Qty": {
                        "type": "number",
                        "description": "Item Quantity"
                    },
                    "OriginalOrderQty": {
                        "type": "number",
                        "description": "Original order quantity"
                    },
                    "QtyUOM": {
                        "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/QtyUOM"
                    },
                    "UCValue": {
                        "type": "number",
                        "description": "Unit cost"
                    },
                    "OriginalOrderUCValue": {
                        "type": "number",
                        "description": "Original Unit Cost"
                    },
                    "UCCurrencyCode": {
                        "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/CurrencyCode"
                    },
                    "EstimatedShipDate": {
                        "type": "string",
                        "description": "Estimated Shipping Date",
                        "format": "date"
                    },
                    "SupplierOrderId": {
                        "type": "string",
                        "description": "Suppliers Order ID"
                    },
                    "BuyerItemId": {
                        "type": "string",
                        "description": "Buyer Item ID"
                    },
                    "SupplierItemId": {
                        "type": "string",
                        "description": "Supplier Item ID"
                    },
                    "BarCodeId": {
                        "type": "string",
                        "description": "Barcode Value"
                    },
                    "BarCodeType": {
                        "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/BarCodeType"
                    },
                    "ShipTo": {
                        "oneOf": [
                            {
                                "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Party"
                            },
                            {
                                "type": "object",
                                "properties": {
                                    "Name": {
                                        "type": "string",
                                        "maxLength": 35
                                    },
                                    "Address": {
                                        "#ref": "https://standards.namm.org/schema/common.json#Address"
                                    }
                                },
                                "required": [
                                    "Address",
                                    "Name"
                                ]
                            }
                        ]
                    }
                }
            }
        }
    },
    "required": [],
    "definitions": {
        "StatusCode": {
            "type": "string",
            "description": "Status Codes for Document and Item (TBD)",
            "enum": [
                "1",
                "2",
                "3",
                "Changes",
                "C1"
            ]
        }
    }
}

=== namm-standards/namm-json/examples/po_status_example.json
{
    "Version": 2020.1,
    "Id": "B78DD4DC-09EB-4D47-AD3C-FF2105399CDE",
    "POStatusRequestId": "8814043038988",
    "Timestamp": "2020-01-02T01:21:44-0500",
    "BuyerOrderId": "8814043038988",
    "DateOrdered": "2019-12-31",
    "BuyerName": "",
    "Supplier": {
      "PartyId": "0670716000009",
      "PartyIdType": "GLN",
      "Name": "Korg USA Inc.",
      "Address": {
        "Attn": "",
        "Address1": "316 S SERVICE RD",
        "Address2": "",
        "Address3": "",
        "City": "MELVILLE",
        "State": "NY",
        "PostalCode": "117473228",
        "Country": "USA",
        "CountryCode": "US"
      }
    },
    "SoldTo": {
      "PartyId": "698765768754",
      "PartyIdType": "GLN",
      "Name": "Bill's Music",
      "Address": {
        "Attn": "Accounts Payable",
        "Address1": "1 FLUSHING AVE",
        "Address2": "",
        "Address3": "",
        "City": "BROOKLYN",
        "State": "NY",
        "PostalCode": "11205",
        "Country": "USA",
        "CountryCode": "US"
      }
    },
    "StatusCode": "C1",
    "PaymentTerms": {
      "StatusCode": "0",
      "StatusMessage": "",
      "TermsCode": "P002"
    },
    "ShipmentTerms": {
      "StatusCode": "0"
    },
    "ShipTo": {
        "PartyId": "698765768754",
        "PartyIdType": "GLN",
        "Name": "Bill's Music",
        "Address": {
        "Attn": "",
        "Address1": "1 FLUSHING AVE",
        "Address2": "",
        "Address3": "",
        "City": "BROOKLYN",
        "State": "NY",
        "PostalCode": "11205",
        "Country": "USA",
        "CountryCode": "US"
      }
    },
    "Items": [
        {
          "POLineNbr": 1,
          "SequenceNbr": 1,
          "StatusCode": "Changes",
          "StatusMessage": "",
          "Qty": 1,
          "OriginalOrderQty": 1,
          "QtyUOM": "Each",
          "UCValue": 47.00,
          "OriginalOrderUCValue": 30.75,
          "UCCurrencyCode": "USD",
          "EstimatedShipDate": "2014-05-07",
          "SupplierOrderId": "OM99574453",
          "BuyerItemId": "KXXFKM2",
          "SupplierItemId": "XFKM2",
          "BarCodeId": "654321",
          "BarCodeType": "PartNumber",
          "ShipTo": {
            "Name": "Bill's Music",
            "Address": {
              "Attn": "",
              "Address1": "1 FLUSHING AVE",
              "Address2": "",
              "Address3": "",
              "City": "BROOKLYN",
              "State": "NY",
              "PostalCode": "11205",
              "Country": "USA",
              "CountryCode": "US"
            }
          }
        },
        {
          "POLineNbr": 2,
          "SequenceNbr": 1,
          "StatusCode": "Changes",
          "StatusMessage": "",
          "Qty": 2,
          "OriginalOrderQty": 6,
          "QtyUOM": "Each",
          "UCValue": 16.80,
          "OriginalOrderUCValue": 16.80,
          "UCCurrencyCode": "USD",
          "EstimatedShipDate": "2014-06-12",
          "SupplierOrderId": "OM99574453",
          "BuyerItemId": "KXGA1",
          "SupplierItemId": "GA1",
          "BarCodeId": "4959112069329",
          "BarCodeType": "GTIN-13"
        },
        {
          "POLineNbr": 2,
          "SequenceNbr": 2,
          "StatusCode": "Changes",
          "StatusMessage": "",
          "Qty": 4,
          "OriginalOrderQty": 6,
          "QtyUOM": "Each",
          "UCValue": 16.80,
          "OriginalOrderUCValue": 16.80,
          "UCCurrencyCode": "USD",
          "SupplierOrderId": "OM99574453",
          "BuyerItemId": "KXGA1",
          "SupplierItemId": "GA1",
          "BarCodeId": "4959112069329",
          "BarCodeType": "GTIN-13"
        }
      ]
    
 
}
